[package]
name = "eth1-http"
version = "0.1.0"
authors = ["Paul Hauner <paul@paulhauner.com>"]
edition = "2018"

[dev-dependencies]
eth1_test_rig = { path = "../../tests/eth1_test_rig" }

[dependencies]
reqwest = "0.9"
tokio = "0.1.17"
tokio-core = "0.1.17"
futures = "0.1.25"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
hex = "0.4"
types = { path = "../../eth2/types"}
