[package]
name = "eth2-libp2p"
version = "0.1.0"
authors = ["Age Manning <Age@AgeManning.com>"]
edition = "2018"

[dependencies]
#SigP repository 
libp2p =  { git = "https://github.com/SigP/rust-libp2p", rev = "8ac9c744197faaadc0e2b64fed7470ac4e2a41ca" }
enr =  { git = "https://github.com/SigP/rust-libp2p/", rev = "8ac9c744197faaadc0e2b64fed7470ac4e2a41ca", features = ["serde"] }
types = { path =  "../../eth2/types" }
version = { path = "../version" }
eth2_ssz = "0.1"
eth2_ssz_derive = "0.1"
lighthouse_metrics = { path = "../../eth2/utils/lighthouse_metrics" }
unsigned-varint = "0.2.2"
common = { path = "../common" }
lazy_static = "1.3.0"
serde = "1.0"
