name: test-suite

on: [push]

jobs:
  release-tests-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install ganache-cli
      run: sudo npm install -g ganache-cli
    - name: Run release tests
      run: cargo test --release --all
  debug-tests-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install ganache-cli
      run: sudo npm install -g ganache-cli
    - name: Run debug tests & check formatting
      run: cargo test --all
    - name: Check formatting with cargo fmt
      run: cargo fmt --all -- check
  ef-tests-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Download test vectors
      run: make make-ef-tests
    - name: Run eth2.0-spec-tests without fake_crypto
      run: cargo test --manifest-path tests/ef_tests/Cargo.toml --release --features ef_tests
    - name: Run eth2.0-spec-tests with fake_crypto
      run: cargo test --manifest-path tests/ef_tests/Cargo.toml --release --features ef_tests,fake_crypto
